package View;

import Model.PlannedMealModel;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author micah
 */
public class DayPlanView extends javax.swing.JPanel {

	/**
	 * Creates new form DayPlanView
	 */
	public DayPlanView() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                lblWeekday = new javax.swing.JLabel();
                paneMealList = new javax.swing.JScrollPane();
                lstPlannedMeals = new javax.swing.JList<>();
                btnAddMeal = new javax.swing.JButton();
                lblDate = new javax.swing.JLabel();

                lblWeekday.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
                lblWeekday.setText("Monday");

                lstPlannedMeals.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                paneMealList.setViewportView(lstPlannedMeals);

                btnAddMeal.setText("+");

                lblDate.setText("02/21/2052");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(paneMealList, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(lblDate)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnAddMeal))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(lblWeekday)
                                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblWeekday)
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAddMeal)
                                        .addComponent(lblDate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(paneMealList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

	public void setAddMealListener(ActionListener listener){
		btnAddMeal.addActionListener(listener);
	}

	public void setMealSelectedListener(ListSelectionListener listener){
		lstPlannedMeals.addListSelectionListener(listener);
	}

	public void setWeekdayText(String text){
		lblWeekday.setText(text);
	}

	public void setDateText(String text){
		lblDate.setText(text);
	}

	public void clearSelected(){
		lstPlannedMeals.clearSelection();
	}

	public void setPlannedMealsList(List<PlannedMealModel> plannedMeals){
		DefaultListModel<PlannedMealModel> listModel = new DefaultListModel<>();
		plannedMeals.stream().forEach(meal -> listModel.addElement(meal));
		lstPlannedMeals.setModel(listModel);
	}


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAddMeal;
        private javax.swing.JLabel lblDate;
        private javax.swing.JLabel lblWeekday;
        private javax.swing.JList<PlannedMealModel> lstPlannedMeals;
        private javax.swing.JScrollPane paneMealList;
        // End of variables declaration//GEN-END:variables
}
