/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.PlannedMealModel;
import Model.RecipeModel;
import java.awt.event.ActionListener;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultListModel;

/**
 *
 * @author micah
 */
public class MealPlanPageView extends javax.swing.JPanel {

	/**
	 * Creates new form MealPlanView
	 */
	public MealPlanPageView() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                java.awt.GridBagConstraints gridBagConstraints;

                jProgressBar1 = new javax.swing.JProgressBar();
                pnlWeekPlans = new javax.swing.JPanel();
                dayPlanSunday = new View.DayPlanView();
                dayPlanMonday = new View.DayPlanView();
                dayPlanTuesday = new View.DayPlanView();
                dayPlanWednesday = new View.DayPlanView();
                dayPlanThursday = new View.DayPlanView();
                dayPlanFriday = new View.DayPlanView();
                dayPlanSaturday = new View.DayPlanView();
                jPanel1 = new javax.swing.JPanel();
                sPaneRecipes = new javax.swing.JScrollPane();
                lstRecipes = new javax.swing.JList<>();
                lstRequiredRecipes = new javax.swing.JLabel();
                lblMealTitle = new javax.swing.JLabel();
                lblMealTime = new javax.swing.JLabel();
                btnDeletePlannedMeal = new javax.swing.JButton();
                btnEditPlannedMeal = new javax.swing.JButton();
                lblMealType = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();
                jPanel2 = new javax.swing.JPanel();
                lblTitle = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                btnBack = new javax.swing.JButton();
                btnNext = new javax.swing.JButton();
                jSeparator2 = new javax.swing.JSeparator();

                pnlWeekPlans.setLayout(new java.awt.GridLayout(1, 0));
                pnlWeekPlans.add(dayPlanSunday);
                pnlWeekPlans.add(dayPlanMonday);
                pnlWeekPlans.add(dayPlanTuesday);
                pnlWeekPlans.add(dayPlanWednesday);
                pnlWeekPlans.add(dayPlanThursday);
                pnlWeekPlans.add(dayPlanFriday);
                pnlWeekPlans.add(dayPlanSaturday);

                sPaneRecipes.setViewportView(lstRecipes);

                lstRequiredRecipes.setText("Required Recipes");

                lblMealTitle.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
                lblMealTitle.setText("Fish and Chips");

                lblMealTime.setFont(new java.awt.Font("sansserif", 2, 14)); // NOI18N
                lblMealTime.setText("02/21/2052 - 8:02pm");

                btnDeletePlannedMeal.setText("Delete");

                btnEditPlannedMeal.setText("Edit");

                lblMealType.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
                lblMealType.setText("Dinner");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnDeletePlannedMeal)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnEditPlannedMeal))
                                        .addComponent(lblMealTitle)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblMealType)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblMealTime)))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lstRequiredRecipes)
                                        .addComponent(sPaneRecipes, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(lstRequiredRecipes)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sPaneRecipes, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblMealType)
                                                        .addComponent(lblMealTime, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblMealTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(52, 52, 52)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btnDeletePlannedMeal)
                                                        .addComponent(btnEditPlannedMeal))))
                                .addContainerGap(77, Short.MAX_VALUE))
                );

                lblTitle.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
                lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lblTitle.setText("Weekly Meal Plan");

                jPanel3.setLayout(new java.awt.GridBagLayout());

                btnBack.setText("<");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 0;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 0);
                jPanel3.add(btnBack, gridBagConstraints);

                btnNext.setText(">");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 0;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(6, 18, 6, 6);
                jPanel3.add(btnNext, gridBagConstraints);

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(pnlWeekPlans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator2))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlWeekPlans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
        }// </editor-fold>//GEN-END:initComponents

	public DayPlanView getSundayPlanView(){
		return dayPlanSunday;
	}
	public DayPlanView getMondayPlanView(){
		return dayPlanMonday;
	}
	public DayPlanView getTuesdayPlanView(){
		return dayPlanTuesday;
	}
	public DayPlanView getWednesdayPlanView(){
		return dayPlanWednesday;
	}
	public DayPlanView getThursdayPlanView(){
		return dayPlanThursday;
	}
	public DayPlanView getFridayPlanView(){
		return dayPlanFriday;
	}
	public DayPlanView getSaturdayPlanView(){
		return dayPlanSaturday;
	}

	public void setSelectedPlannedMeal(PlannedMealModel plannedMeal){
		if (plannedMeal == null) return;

		try {
			lblMealType.setText(plannedMeal.getMealType());
			lblMealTime.setText(plannedMeal.getPlannedTime().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")));
			lblMealTitle.setText(plannedMeal.getMeal().getName());

			DefaultListModel<RecipeModel> listModel = new DefaultListModel<>();
			plannedMeal.getRecipes().stream().forEach(recipe -> listModel.addElement(recipe));
			lstRecipes.setModel(listModel);
		} catch (Exception e){
			System.out.println("error loading plannedMeal...");
		}
	}

	public void setNextListener(ActionListener listener){
		btnNext.addActionListener(listener);
	}

	public void setBackListener(ActionListener listener){
		btnBack.addActionListener(listener);
	}


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnDeletePlannedMeal;
        private javax.swing.JButton btnEditPlannedMeal;
        private javax.swing.JButton btnNext;
        private View.DayPlanView dayPlanFriday;
        private View.DayPlanView dayPlanMonday;
        private View.DayPlanView dayPlanSaturday;
        private View.DayPlanView dayPlanSunday;
        private View.DayPlanView dayPlanThursday;
        private View.DayPlanView dayPlanTuesday;
        private View.DayPlanView dayPlanWednesday;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JProgressBar jProgressBar1;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JSeparator jSeparator2;
        private javax.swing.JLabel lblMealTime;
        private javax.swing.JLabel lblMealTitle;
        private javax.swing.JLabel lblMealType;
        private javax.swing.JLabel lblTitle;
        private javax.swing.JList<RecipeModel> lstRecipes;
        private javax.swing.JLabel lstRequiredRecipes;
        private javax.swing.JPanel pnlWeekPlans;
        private javax.swing.JScrollPane sPaneRecipes;
        // End of variables declaration//GEN-END:variables
}
