/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.PlannedMealModel;
import Model.RecipeModel;
import java.awt.event.ActionListener;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultListModel;

/**
 *
 * @author micah
 */
public class MealPlanPageView extends javax.swing.JPanel {

	/**
	 * Creates new form MealPlanView
	 */
	public MealPlanPageView() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jProgressBar1 = new javax.swing.JProgressBar();
                pnlWeekPlans = new javax.swing.JPanel();
                dayPlanSunday = new View.DayPlanView();
                dayPlanMonday = new View.DayPlanView();
                dayPlanTuesday = new View.DayPlanView();
                dayPlanWednesday = new View.DayPlanView();
                dayPlanThursday = new View.DayPlanView();
                dayPlanFriday = new View.DayPlanView();
                dayPlanSaturday = new View.DayPlanView();
                lblTitle = new javax.swing.JLabel();
                btnNext = new javax.swing.JButton();
                btnBack = new javax.swing.JButton();
                jPanel1 = new javax.swing.JPanel();
                sPaneRecipes = new javax.swing.JScrollPane();
                lstRecipes = new javax.swing.JList<>();
                lstRequiredRecipes = new javax.swing.JLabel();
                lblMealTitle = new javax.swing.JLabel();
                lblMealTime = new javax.swing.JLabel();
                lblMealType = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();

                javax.swing.GroupLayout pnlWeekPlansLayout = new javax.swing.GroupLayout(pnlWeekPlans);
                pnlWeekPlans.setLayout(pnlWeekPlansLayout);
                pnlWeekPlansLayout.setHorizontalGroup(
                        pnlWeekPlansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlWeekPlansLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(dayPlanSunday, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dayPlanMonday, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dayPlanTuesday, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dayPlanWednesday, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dayPlanThursday, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dayPlanFriday, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dayPlanSaturday, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                pnlWeekPlansLayout.setVerticalGroup(
                        pnlWeekPlansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlWeekPlansLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlWeekPlansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlWeekPlansLayout.createSequentialGroup()
                                                .addComponent(dayPlanSaturday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(dayPlanSunday, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(pnlWeekPlansLayout.createSequentialGroup()
                                                .addGroup(pnlWeekPlansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(dayPlanMonday, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(dayPlanWednesday, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(dayPlanTuesday, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(dayPlanFriday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(dayPlanThursday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                );

                lblTitle.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
                lblTitle.setText("Weekly Meal Plan");

                btnNext.setText(">");

                btnBack.setText("<");

                sPaneRecipes.setViewportView(lstRecipes);

                lstRequiredRecipes.setText("Required Recipes");

                lblMealTitle.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
                lblMealTitle.setText("Fish and Chips");

                lblMealTime.setFont(new java.awt.Font("sansserif", 2, 14)); // NOI18N
                lblMealTime.setText("02/21/2052 - 8:02pm");

                lblMealType.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
                lblMealType.setText("Dinner");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(lblMealTitle))
                                        .addComponent(lblMealTime)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addComponent(lblMealType)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lstRequiredRecipes)
                                        .addComponent(sPaneRecipes, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 65, 65))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(lstRequiredRecipes)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sPaneRecipes, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(55, 55, 55)
                                                .addComponent(lblMealTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblMealTime, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblMealType)))
                                .addContainerGap(36, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblTitle)
                                .addGap(335, 335, 335))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNext)
                                .addGap(417, 417, 417))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(pnlWeekPlans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lblTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnNext)
                                        .addComponent(btnBack))
                                .addGap(18, 18, 18)
                                .addComponent(pnlWeekPlans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

	public DayPlanView getSundayPlanView(){
		return dayPlanSunday;
	}
	public DayPlanView getMondayPlanView(){
		return dayPlanMonday;
	}
	public DayPlanView getTuesdayPlanView(){
		return dayPlanTuesday;
	}
	public DayPlanView getWednesdayPlanView(){
		return dayPlanWednesday;
	}
	public DayPlanView getThursdayPlanView(){
		return dayPlanThursday;
	}
	public DayPlanView getFridayPlanView(){
		return dayPlanFriday;
	}
	public DayPlanView getSaturdayPlanView(){
		return dayPlanSaturday;
	}

	public void setSelectedPlannedMeal(PlannedMealModel plannedMeal){
		if (plannedMeal == null) return;

		try {
			lblMealType.setText(plannedMeal.getMealType());
			lblMealTime.setText(plannedMeal.getPlannedTime().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")));
			lblMealTitle.setText(plannedMeal.getMeal().getName());

			DefaultListModel<RecipeModel> listModel = new DefaultListModel<>();
			plannedMeal.getRecipes().stream().forEach(recipe -> listModel.addElement(recipe));
			lstRecipes.setModel(listModel);
		} catch (Exception e){
			System.out.println("error loading plannedMeal...");
		}
	}

	public void setNextListener(ActionListener listener){
		btnNext.addActionListener(listener);
	}

	public void setBackListener(ActionListener listener){
		btnBack.addActionListener(listener);
	}


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnNext;
        private View.DayPlanView dayPlanFriday;
        private View.DayPlanView dayPlanMonday;
        private View.DayPlanView dayPlanSaturday;
        private View.DayPlanView dayPlanSunday;
        private View.DayPlanView dayPlanThursday;
        private View.DayPlanView dayPlanTuesday;
        private View.DayPlanView dayPlanWednesday;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JProgressBar jProgressBar1;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JLabel lblMealTime;
        private javax.swing.JLabel lblMealTitle;
        private javax.swing.JLabel lblMealType;
        private javax.swing.JLabel lblTitle;
        private javax.swing.JList<RecipeModel> lstRecipes;
        private javax.swing.JLabel lstRequiredRecipes;
        private javax.swing.JPanel pnlWeekPlans;
        private javax.swing.JScrollPane sPaneRecipes;
        // End of variables declaration//GEN-END:variables
}
