/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.RecipeModel;
import java.util.List;
import javax.swing.event.DocumentListener;

/**
 *
 * @author micah
 */
public class RecipePageView extends javax.swing.JPanel {

	/**
	 * Creates new form RecipePageView
	 */
	public RecipePageView() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jProgressBar1 = new javax.swing.JProgressBar();
                txtNameSearch = new javax.swing.JTextField();
                txtCategorySearch = new javax.swing.JTextField();
                txtIngredientSearch = new javax.swing.JTextField();
                lstRecipes = new javax.swing.JScrollPane();
                jList1 = new javax.swing.JList<>();
                lblRecipes = new javax.swing.JLabel();
                lblName = new javax.swing.JLabel();
                lblCategory = new javax.swing.JLabel();
                lblIngredients = new javax.swing.JLabel();
                recipeViewPanel = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTextArea1 = new javax.swing.JTextArea();
                jSeparator1 = new javax.swing.JSeparator();
                jLabel3 = new javax.swing.JLabel();
                jSeparator2 = new javax.swing.JSeparator();

                txtNameSearch.setToolTipText("ex: Burger");

                txtCategorySearch.setToolTipText("ex: Dinner, Brunch");

                txtIngredientSearch.setToolTipText("ex: spinach, tomatoe, rice...");

                jList1.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
                        public int getSize() { return strings.length; }
                        public String getElementAt(int i) { return strings[i]; }
                });
                lstRecipes.setViewportView(jList1);

                lblRecipes.setText("Recipes");

                lblName.setText("Name");

                lblCategory.setText("Category");

                lblIngredients.setText("Ingredients");

                jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
                jLabel1.setText("Sample Recipe Name");

                jLabel2.setFont(new java.awt.Font("Chandas", 2, 18)); // NOI18N
                jLabel2.setText("Sample Category");

                jTextArea1.setEditable(false);
                jTextArea1.setColumns(20);
                jTextArea1.setRows(5);
                jTextArea1.setText("1. do something to food\n2. do something else to food\n3. do something more else to food");
                jScrollPane1.setViewportView(jTextArea1);

                jLabel3.setText("Instructions");

                javax.swing.GroupLayout recipeViewPanelLayout = new javax.swing.GroupLayout(recipeViewPanel);
                recipeViewPanel.setLayout(recipeViewPanelLayout);
                recipeViewPanelLayout.setHorizontalGroup(
                        recipeViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(recipeViewPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(recipeViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(recipeViewPanelLayout.createSequentialGroup()
                                                .addGroup(recipeViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane1)
                                                        .addComponent(jSeparator1)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addContainerGap())
                                        .addGroup(recipeViewPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                );
                recipeViewPanelLayout.setVerticalGroup(
                        recipeViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(recipeViewPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(1, 1, 1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(244, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblName))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtCategorySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblCategory))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblIngredients)
                                                        .addComponent(txtIngredientSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lstRecipes, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblRecipes))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(recipeViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap(124, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator2))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblName)
                                        .addComponent(lblCategory)
                                        .addComponent(lblIngredients))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCategorySearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtIngredientSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblRecipes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(recipeViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lstRecipes))
                                .addContainerGap())
                );
        }// </editor-fold>//GEN-END:initComponents


	public void setFilterListeners(DocumentListener listener){
		txtCategorySearch.getDocument().addDocumentListener(listener);
		txtIngredientSearch.getDocument().addDocumentListener(listener);
		txtNameSearch.getDocument().addDocumentListener(listener);
	}


	public String getCategoryText(){
		return this.txtCategorySearch.getText();
	}

	public void setCategoryText(String text){
		this.txtCategorySearch.setText(text);
	}

	public String getNameText(){
		return this.txtNameSearch.getText();
	}

	public void setNameText(String text){
		this.txtNameSearch.setText(text);
	}

	public String getIngredientText(){
		return this.txtIngredientSearch.getText();
	}

	public void setIngredientText(String text){
		this.txtIngredientSearch.setText(text);
	}

	public void setRecipeList(List<RecipeModel> recipes){
		String[] labels = recipes.stream().map(recipe -> recipe.getName()).toArray(String[]::new);

		jList1.setListData(labels);
	}


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JList<String> jList1;
        private javax.swing.JProgressBar jProgressBar1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JSeparator jSeparator2;
        private javax.swing.JTextArea jTextArea1;
        private javax.swing.JLabel lblCategory;
        private javax.swing.JLabel lblIngredients;
        private javax.swing.JLabel lblName;
        private javax.swing.JLabel lblRecipes;
        private javax.swing.JScrollPane lstRecipes;
        private javax.swing.JPanel recipeViewPanel;
        private javax.swing.JTextField txtCategorySearch;
        private javax.swing.JTextField txtIngredientSearch;
        private javax.swing.JTextField txtNameSearch;
        // End of variables declaration//GEN-END:variables
}
