/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.RecipeModel;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.event.DocumentListener;

/**
 *
 * @author micah
 */
public class RecipePageView extends javax.swing.JPanel {

	/**
	 * Creates new form RecipePageView
	 */
	public RecipePageView() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                txtNameSearch = new javax.swing.JTextField();
                txtCategorySearch = new javax.swing.JTextField();
                txtIngredientSearch = new javax.swing.JTextField();
                lblFilters = new javax.swing.JLabel();
                lstRecipes = new javax.swing.JScrollPane();
                jList1 = new javax.swing.JList<>();
                lblRecipes = new javax.swing.JLabel();

                txtNameSearch.setText("Search for item here...");

                txtCategorySearch.setText("Category...");

                txtIngredientSearch.setText("Ingredients (ex: spinach, tomatoes, rice, ...)");

                lblFilters.setText("Filters");

                jList1.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
                        public int getSize() { return strings.length; }
                        public String getElementAt(int i) { return strings[i]; }
                });
                lstRecipes.setViewportView(jList1);

                lblRecipes.setText("Recipes");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblRecipes)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblFilters)
                                                .addComponent(txtIngredientSearch)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(txtNameSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtCategorySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(lstRecipes)))
                                .addContainerGap(22, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblFilters)
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCategorySearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIngredientSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRecipes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lstRecipes, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
        }// </editor-fold>//GEN-END:initComponents

	public void setRecipeList(ArrayList<RecipeModel> recipes){
		DefaultListModel model = new DefaultListModel();

		for (RecipeModel recipe : recipes){
			model.addElement(recipe.getName());
		}

		this.jList1 = new JList(model);
	}

	public String getCategoryText(){
		return this.txtCategorySearch.getText();
	}

	public void setCategoryText(String text){
		this.txtCategorySearch.setText(text);
	}

	public String getNameText(){
		return this.txtNameSearch.getText();
	}

	public void setNameText(String text){
		this.txtNameSearch.setText(text);
	}

	public String getIngredientText(){
		return this.txtIngredientSearch.getText();
	}

	public void setIngredientText(String text){
		this.txtIngredientSearch.setText(text);
	}

	public void addCategorySearchListener(DocumentListener listener){
		this.txtCategorySearch.getDocument().addDocumentListener(listener);
	}
	public void addNameSearchListener(DocumentListener listener){
		this.txtNameSearch.getDocument().addDocumentListener(listener);
	}
	public void addIngredientSearchListener(DocumentListener listener){
		this.txtIngredientSearch.getDocument().addDocumentListener(listener);
	}


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JList<String> jList1;
        private javax.swing.JLabel lblFilters;
        private javax.swing.JLabel lblRecipes;
        private javax.swing.JScrollPane lstRecipes;
        private javax.swing.JTextField txtCategorySearch;
        private javax.swing.JTextField txtIngredientSearch;
        private javax.swing.JTextField txtNameSearch;
        // End of variables declaration//GEN-END:variables
}
