/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.RecipeModel;
import java.util.List;
import javax.swing.event.DocumentListener;

/**
 *
 * @author micah
 */
public class RecipePageView extends javax.swing.JPanel {

	/**
	 * Creates new form RecipePageView
	 */
	public RecipePageView() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jProgressBar1 = new javax.swing.JProgressBar();
                txtNameSearch = new javax.swing.JTextField();
                txtCategorySearch = new javax.swing.JTextField();
                txtIngredientSearch = new javax.swing.JTextField();
                lstRecipes = new javax.swing.JScrollPane();
                jList1 = new javax.swing.JList<>();
                lblRecipes = new javax.swing.JLabel();
                lblName = new javax.swing.JLabel();
                lblCategory = new javax.swing.JLabel();
                lblIngredients = new javax.swing.JLabel();

                txtNameSearch.setToolTipText("ex: Burger");

                txtCategorySearch.setToolTipText("ex: Dinner, Brunch");

                txtIngredientSearch.setToolTipText("ex: spinach, tomatoe, rice...");

                jList1.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
                        public int getSize() { return strings.length; }
                        public String getElementAt(int i) { return strings[i]; }
                });
                lstRecipes.setViewportView(jList1);

                lblRecipes.setText("Recipes");

                lblName.setText("Name");

                lblCategory.setText("Category");

                lblIngredients.setText("Ingredients");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lstRecipes)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblRecipes)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lblName))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtCategorySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lblCategory))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lblIngredients)
                                                                        .addComponent(txtIngredientSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblName)
                                        .addComponent(lblCategory)
                                        .addComponent(lblIngredients))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCategorySearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtIngredientSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRecipes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lstRecipes, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                                .addContainerGap())
                );
        }// </editor-fold>//GEN-END:initComponents


	public void setFilterListeners(DocumentListener listener){
		txtCategorySearch.getDocument().addDocumentListener(listener);
		txtIngredientSearch.getDocument().addDocumentListener(listener);
		txtNameSearch.getDocument().addDocumentListener(listener);
	}


	public String getCategoryText(){
		return this.txtCategorySearch.getText();
	}

	public void setCategoryText(String text){
		this.txtCategorySearch.setText(text);
	}

	public String getNameText(){
		return this.txtNameSearch.getText();
	}

	public void setNameText(String text){
		this.txtNameSearch.setText(text);
	}

	public String getIngredientText(){
		return this.txtIngredientSearch.getText();
	}

	public void setIngredientText(String text){
		this.txtIngredientSearch.setText(text);
	}

	public void setRecipeList(List<RecipeModel> recipes){
		String[] labels = recipes.stream().map(recipe -> recipe.getName()).toArray(String[]::new);

		jList1.setListData(labels);
	}


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JList<String> jList1;
        private javax.swing.JProgressBar jProgressBar1;
        private javax.swing.JLabel lblCategory;
        private javax.swing.JLabel lblIngredients;
        private javax.swing.JLabel lblName;
        private javax.swing.JLabel lblRecipes;
        private javax.swing.JScrollPane lstRecipes;
        private javax.swing.JTextField txtCategorySearch;
        private javax.swing.JTextField txtIngredientSearch;
        private javax.swing.JTextField txtNameSearch;
        // End of variables declaration//GEN-END:variables
}
