/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Page.MealPlan;

import Model.PlannedMealModel;
import Model.RecipeModel;
import View.Page.MealPlan.DayPlanView;
import java.awt.event.ActionListener;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author micah
 */
public class MealPlanView extends javax.swing.JPanel {

	/**
	 * Creates new form MealPlanView
	 */
	public MealPlanView() {
		initComponents();
		hideViews();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jProgressBar1 = new javax.swing.JProgressBar();
                pnlWeekPlans = new javax.swing.JPanel();
                dayPlanSunday = new View.Page.MealPlan.DayPlanView();
                dayPlanMonday = new View.Page.MealPlan.DayPlanView();
                dayPlanTuesday = new View.Page.MealPlan.DayPlanView();
                dayPlanWednesday = new View.Page.MealPlan.DayPlanView();
                dayPlanThursday = new View.Page.MealPlan.DayPlanView();
                dayPlanFriday = new View.Page.MealPlan.DayPlanView();
                dayPlanSaturday = new View.Page.MealPlan.DayPlanView();
                panelSelectedItem = new javax.swing.JPanel();
                sPaneRecipes = new javax.swing.JScrollPane();
                lstRecipes = new javax.swing.JList<>();
                lstRequiredRecipes = new javax.swing.JLabel();
                lblMealTitle = new javax.swing.JLabel();
                lblMealTime = new javax.swing.JLabel();
                btnDeletePlannedMeal = new javax.swing.JButton();
                lblMealType = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();
                jPanel2 = new javax.swing.JPanel();
                lblTitle = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                btnBack = new javax.swing.JButton();
                filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0));
                btnNext = new javax.swing.JButton();
                btnGenerateShoppingList = new javax.swing.JButton();
                jSeparator2 = new javax.swing.JSeparator();
                jPanel1 = new javax.swing.JPanel();

                pnlWeekPlans.setLayout(new java.awt.GridLayout(1, 0));
                pnlWeekPlans.add(dayPlanSunday);
                pnlWeekPlans.add(dayPlanMonday);
                pnlWeekPlans.add(dayPlanTuesday);
                pnlWeekPlans.add(dayPlanWednesday);
                pnlWeekPlans.add(dayPlanThursday);
                pnlWeekPlans.add(dayPlanFriday);
                pnlWeekPlans.add(dayPlanSaturday);

                panelSelectedItem.setMaximumSize(new java.awt.Dimension(477, 168));
                panelSelectedItem.setMinimumSize(new java.awt.Dimension(477, 168));

                lstRecipes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                lstRecipes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                sPaneRecipes.setViewportView(lstRecipes);

                lstRequiredRecipes.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
                lstRequiredRecipes.setText("Recipes");

                lblMealTitle.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
                lblMealTitle.setText("Fish and Chips");

                lblMealTime.setFont(new java.awt.Font("sansserif", 2, 14)); // NOI18N
                lblMealTime.setText("02/21/2052 - 8:02pm");

                btnDeletePlannedMeal.setText("Delete");

                lblMealType.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
                lblMealType.setText("Dinner");

                javax.swing.GroupLayout panelSelectedItemLayout = new javax.swing.GroupLayout(panelSelectedItem);
                panelSelectedItem.setLayout(panelSelectedItemLayout);
                panelSelectedItemLayout.setHorizontalGroup(
                        panelSelectedItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelSelectedItemLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panelSelectedItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelSelectedItemLayout.createSequentialGroup()
                                                .addComponent(lblMealType)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblMealTime))
                                        .addGroup(panelSelectedItemLayout.createSequentialGroup()
                                                .addGroup(panelSelectedItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblMealTitle)
                                                        .addComponent(btnDeletePlannedMeal))
                                                .addGap(146, 146, 146)
                                                .addGroup(panelSelectedItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lstRequiredRecipes)
                                                        .addComponent(sPaneRecipes, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap())
                );
                panelSelectedItemLayout.setVerticalGroup(
                        panelSelectedItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelSelectedItemLayout.createSequentialGroup()
                                .addGroup(panelSelectedItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelSelectedItemLayout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addGroup(panelSelectedItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblMealType)
                                                        .addComponent(lblMealTime, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(6, 6, 6)
                                                .addComponent(lblMealTitle)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnDeletePlannedMeal))
                                        .addGroup(panelSelectedItemLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(lstRequiredRecipes)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sPaneRecipes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                lblTitle.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
                lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lblTitle.setText("Weekly Meal Plan");

                jPanel3.setLayout(new java.awt.GridBagLayout());

                btnBack.setText("<");
                jPanel3.add(btnBack, new java.awt.GridBagConstraints());
                jPanel3.add(filler1, new java.awt.GridBagConstraints());

                btnNext.setText(">");
                jPanel3.add(btnNext, new java.awt.GridBagConstraints());

                btnGenerateShoppingList.setText("Generate Shopping List");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGenerateShoppingList)
                                .addContainerGap())
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblTitle)
                                        .addComponent(btnGenerateShoppingList))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(panelSelectedItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(183, 183, 183)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(57, 57, 57))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(pnlWeekPlans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jSeparator2))
                                                .addContainerGap())))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlWeekPlans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(49, 49, 49)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(panelSelectedItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(48, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

	public void setupWeekView(List<DayPlanView> dayPlanViews) {
		pnlWeekPlans.removeAll();
		dayPlanViews.stream().forEach(view -> pnlWeekPlans.add(view));
		revalidate();
		repaint();
	}
	
	public void hideViews(){
		panelSelectedItem.setVisible(false);
	}
	
	public void showViews(){
		panelSelectedItem.setVisible(true);
	}

	public void setSelectedPlannedMeal(PlannedMealModel plannedMeal){
		if (plannedMeal == null){
			hideViews();
			return;
		}
		showViews();
		try {
			lblMealType.setText(plannedMeal.getMealType());
			lblMealTime.setText(plannedMeal.getPlannedTime().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")));
			lblMealTitle.setText(plannedMeal.getMeal().getName());

			DefaultListModel<RecipeModel> listModel = new DefaultListModel<>();
			plannedMeal.getRecipes().stream().forEach(recipe -> listModel.addElement(recipe));
			lstRecipes.setModel(listModel);
		} catch (Exception e){
			System.out.println("error loading plannedMeal...");
		}
	}

	public void setNextListener(ActionListener listener){
		btnNext.addActionListener(listener);
	}

	public void setBackListener(ActionListener listener){
		btnBack.addActionListener(listener);
	}
	
	public void setDeleteListener(ActionListener l){
		btnDeletePlannedMeal.addActionListener(l);
	}

	public void setGenerateShoppingListListener(ActionListener l){
		btnGenerateShoppingList.addActionListener(l);
	}



        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnDeletePlannedMeal;
        private javax.swing.JButton btnGenerateShoppingList;
        private javax.swing.JButton btnNext;
        private View.Page.MealPlan.DayPlanView dayPlanFriday;
        private View.Page.MealPlan.DayPlanView dayPlanMonday;
        private View.Page.MealPlan.DayPlanView dayPlanSaturday;
        private View.Page.MealPlan.DayPlanView dayPlanSunday;
        private View.Page.MealPlan.DayPlanView dayPlanThursday;
        private View.Page.MealPlan.DayPlanView dayPlanTuesday;
        private View.Page.MealPlan.DayPlanView dayPlanWednesday;
        private javax.swing.Box.Filler filler1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JProgressBar jProgressBar1;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JSeparator jSeparator2;
        private javax.swing.JLabel lblMealTime;
        private javax.swing.JLabel lblMealTitle;
        private javax.swing.JLabel lblMealType;
        private javax.swing.JLabel lblTitle;
        private javax.swing.JList<RecipeModel> lstRecipes;
        private javax.swing.JLabel lstRequiredRecipes;
        private javax.swing.JPanel panelSelectedItem;
        private javax.swing.JPanel pnlWeekPlans;
        private javax.swing.JScrollPane sPaneRecipes;
        // End of variables declaration//GEN-END:variables
}
