/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View.Dialog;

import Model.ItemModel;
import Model.NutritionModel;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author micah
 */
public class AddItemView extends javax.swing.JDialog {

	/**
	 * Creates new form AddItemView
	 */
	public AddItemView(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                lblAddItem = new javax.swing.JLabel();
                lblName = new javax.swing.JLabel();
                lblGroup = new javax.swing.JLabel();
                lblNutritionValues = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();
                lblSodium = new javax.swing.JLabel();
                lblFat = new javax.swing.JLabel();
                lblProtein = new javax.swing.JLabel();
                lblSugar = new javax.swing.JLabel();
                lblCalories = new javax.swing.JLabel();
                tfSodium = new javax.swing.JTextField();
                tfFat = new javax.swing.JTextField();
                tfProtein = new javax.swing.JTextField();
                tfSugar = new javax.swing.JTextField();
                tfCalories = new javax.swing.JTextField();
                tfName = new javax.swing.JTextField();
                tfGroup = new javax.swing.JTextField();
                btnSubmit = new javax.swing.JButton();
                btnCancel = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                lblAddItem.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
                lblAddItem.setText("Add New Item");

                lblName.setText("Name");

                lblGroup.setText("Group");

                lblNutritionValues.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
                lblNutritionValues.setText("Nutrition Values");

                lblSodium.setText("Sodium");

                lblFat.setText("Fat");

                lblProtein.setText("Protein");

                lblSugar.setText("Sugar");

                lblCalories.setText("Calories");

                btnSubmit.setText("Submit");

                btnCancel.setText("Cancel");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(81, 81, 81)
                                                .addComponent(lblAddItem))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblName)
                                                        .addComponent(lblGroup))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(tfName)
                                                        .addComponent(tfGroup, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblFat)
                                                        .addComponent(lblSodium)
                                                        .addComponent(lblProtein)
                                                        .addComponent(lblSugar)
                                                        .addComponent(lblCalories))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(tfSodium)
                                                        .addComponent(tfFat)
                                                        .addComponent(tfProtein)
                                                        .addComponent(tfSugar)
                                                        .addComponent(tfCalories, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(23, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(lblNutritionValues)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lblAddItem)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblName)
                                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblGroup)
                                        .addComponent(tfGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(lblNutritionValues)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblSodium)
                                        .addComponent(tfSodium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblFat)
                                        .addComponent(tfFat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblProtein)
                                        .addComponent(tfProtein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblSugar)
                                        .addComponent(tfSugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblCalories)
                                        .addComponent(tfCalories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSubmit)
                                        .addComponent(btnCancel))
                                .addContainerGap(20, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
//	public static void main(String args[]) {
//		/* Set the Nimbus look and feel */
//		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//		 */
//		try {
//			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//				if ("Nimbus".equals(info.getName())) {
//					javax.swing.UIManager.setLookAndFeel(info.getClassName());
//					break;
//				}
//			}
//		} catch (ClassNotFoundException ex) {
//			java.util.logging.Logger.getLogger(AddItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		} catch (InstantiationException ex) {
//			java.util.logging.Logger.getLogger(AddItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		} catch (IllegalAccessException ex) {
//			java.util.logging.Logger.getLogger(AddItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
//			java.util.logging.Logger.getLogger(AddItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		}
//		//</editor-fold>
//
//		/* Create and display the dialog */
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				AddItemView dialog = new AddItemView(new javax.swing.JFrame(), true);
//				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//					@Override
//					public void windowClosing(java.awt.event.WindowEvent e) {
//						System.exit(0);
//					}
//				});
//				dialog.setVisible(true);
//			}
//		});
//	}
//	

	public void setCancelButtonListener(ActionListener listener){
		btnCancel.addActionListener(listener);
	}

	public void setSubmitButtonListener(ActionListener listener){
		btnSubmit.addActionListener(listener);
	}

	public void displayErrorPopup(String message){
		JOptionPane.showMessageDialog(null, message, "Error", JOptionPane.ERROR_MESSAGE);
	}

	public void close(){
		dispose();
		this.setVisible(false);
	}

	public ItemModel getSubmittedItem(){
		try {
			int calories = Integer.parseInt(tfCalories.getText());
			int sodium = Integer.parseInt(tfSodium.getText());
			int sugar = Integer.parseInt(tfSugar.getText());
			int protein = Integer.parseInt(tfProtein.getText());
			int fat = Integer.parseInt(tfFat.getText());

			NutritionModel nutrition = new NutritionModel
				.Builder(-1)
				.calories(calories)
				.fat(fat)
				.sodium(sodium)
				.sugar(sugar)
				.protein(protein)
				.build();

			ItemModel newItem = new ItemModel(-1, tfGroup.getText(), tfName.getText(), nutrition);

			return newItem;

		} catch (Exception e){
			return null;
		}
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCancel;
        private javax.swing.JButton btnSubmit;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JLabel lblAddItem;
        private javax.swing.JLabel lblCalories;
        private javax.swing.JLabel lblFat;
        private javax.swing.JLabel lblGroup;
        private javax.swing.JLabel lblName;
        private javax.swing.JLabel lblNutritionValues;
        private javax.swing.JLabel lblProtein;
        private javax.swing.JLabel lblSodium;
        private javax.swing.JLabel lblSugar;
        private javax.swing.JTextField tfCalories;
        private javax.swing.JTextField tfFat;
        private javax.swing.JTextField tfGroup;
        private javax.swing.JTextField tfName;
        private javax.swing.JTextField tfProtein;
        private javax.swing.JTextField tfSodium;
        private javax.swing.JTextField tfSugar;
        // End of variables declaration//GEN-END:variables
}
