/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View.Dialog;

import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author micah
 */
public class EditPlannedMealView extends javax.swing.JDialog {

	/**
	 * Creates new form EditPlannedMealView
	 */
	public EditPlannedMealView(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                bgTimeButtons = new javax.swing.ButtonGroup();
                lblTimeType = new javax.swing.JLabel();
                lblTime = new javax.swing.JLabel();
                lblMeal = new javax.swing.JLabel();
                lblTitle = new javax.swing.JLabel();
                tfType = new javax.swing.JTextField();
                cbTime = new javax.swing.JComboBox<>();
                lblMealName = new javax.swing.JLabel();
                btnSetMeal = new javax.swing.JButton();
                rbAm = new javax.swing.JRadioButton();
                rbPm = new javax.swing.JRadioButton();
                btnSubmit = new javax.swing.JButton();
                btnCancel = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                lblTimeType.setText("Type");

                lblTime.setText("Time");

                lblMeal.setText("Meal");

                lblTitle.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
                lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lblTitle.setText("Edit Planned Meal");

                cbTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00" }));

                lblMealName.setText("None Selected");

                btnSetMeal.setText("Set");

                bgTimeButtons.add(rbAm);
                rbAm.setSelected(true);
                rbAm.setText("am");

                bgTimeButtons.add(rbPm);
                rbPm.setText("pm");

                btnSubmit.setText("Submit");

                btnCancel.setText("Cancel");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(48, 48, 48)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(btnSubmit)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(lblMeal)
                                                                        .addComponent(lblTime)
                                                                        .addComponent(lblTimeType))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(lblMealName)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(btnSetMeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(cbTime, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(rbAm)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(rbPm))
                                                                        .addComponent(tfType)))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                .addGap(1, 1, 1)
                                                                .addComponent(btnCancel)))
                                                .addGap(0, 42, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTitle)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblTimeType)
                                        .addComponent(tfType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblTime)
                                        .addComponent(cbTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rbAm)
                                        .addComponent(rbPm))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblMeal)
                                        .addComponent(lblMealName)
                                        .addComponent(btnSetMeal))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSubmit)
                                        .addComponent(btnCancel))
                                .addContainerGap(15, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(EditPlannedMealView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(EditPlannedMealView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(EditPlannedMealView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(EditPlannedMealView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				EditPlannedMealView dialog = new EditPlannedMealView(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	public void showError(String message){
		JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
	}

	public void setCancelListener(ActionListener l){
		btnCancel.addActionListener(l);
	}

	public void setSubmitListener(ActionListener l){
		btnSubmit.addActionListener(l);
	}

	public void setSetMealListener(ActionListener l){
		btnSetMeal.addActionListener(l);
	}

	public void setTimeChangeListener(ItemListener l){
		cbTime.addItemListener(l);
	}

	public void setAmListener(ActionListener l){
		rbAm.addActionListener(l);
	}

	public void setPmListener(ActionListener l){
		rbPm.addActionListener(l);
	}

	public void setMealNameText(String name){
		lblMealName.setText(name);
	}

	public String getMealType(){
		return tfType.getText();
	}

	public boolean getIsAm(){
		return rbAm.isSelected();
	}

	public String getTimeString(){
		return cbTime.getSelectedItem().toString();
	}

	public void setSetButtonText(String text){
		btnSetMeal.setText(text);
	}

	public void close(){
		this.dispose();
		this.setVisible(false);
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.ButtonGroup bgTimeButtons;
        private javax.swing.JButton btnCancel;
        private javax.swing.JButton btnSetMeal;
        private javax.swing.JButton btnSubmit;
        private javax.swing.JComboBox<String> cbTime;
        private javax.swing.JLabel lblMeal;
        private javax.swing.JLabel lblMealName;
        private javax.swing.JLabel lblTime;
        private javax.swing.JLabel lblTimeType;
        private javax.swing.JLabel lblTitle;
        private javax.swing.JRadioButton rbAm;
        private javax.swing.JRadioButton rbPm;
        private javax.swing.JTextField tfType;
        // End of variables declaration//GEN-END:variables
}
