/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View.Dialog;

import Model.MealModel;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentListener;

/**
 *
 * @author micah
 */
public class SelectMealView extends javax.swing.JDialog {

	/**
	 * Creates new form SelectMealView
	 */
	public SelectMealView(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                lblTitle = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                lstMeals = new javax.swing.JList<>();
                tfSearch = new javax.swing.JTextField();
                lblSearch = new javax.swing.JLabel();
                btnSelect = new javax.swing.JButton();
                btnCancel = new javax.swing.JButton();
                btnAddMeal = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setUndecorated(true);
                setResizable(false);

                jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

                lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                lblTitle.setText("Select Meal");

                lstMeals.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                jScrollPane1.setViewportView(lstMeals);

                lblSearch.setText("Filter");

                btnSelect.setText("Select");

                btnCancel.setText("Cancel");

                btnAddMeal.setText("Create New Meal");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(btnCancel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnSelect))
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(lblSearch)
                                                                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnAddMeal))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(249, 249, 249)
                                                .addComponent(lblTitle)))
                                .addContainerGap(42, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(16, Short.MAX_VALUE)
                                .addComponent(lblTitle)
                                .addGap(18, 18, 18)
                                .addComponent(lblSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAddMeal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSelect)
                                        .addComponent(btnCancel))
                                .addContainerGap())
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */

	public void displayErrorPopup(String message){
		JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
	}

	public void setCancelListener(ActionListener l) {
		btnCancel.addActionListener(l);
	}

	public void setSelectListener(ActionListener l) {
		btnSelect.addActionListener(l);
	}

	public void setAddMealListener(ActionListener l) {
		btnAddMeal.addActionListener(l);
	}

	public void setFilterListener(DocumentListener l){
		tfSearch.getDocument().addDocumentListener(l);
	}


	public MealModel getSelectedMeal(){
		return lstMeals.getSelectedValue();
	}

	public String getSearchText(){
		return tfSearch.getText();
	}

	public void close(){
		this.dispose();
		this.setVisible(false);
	}

	public void setMealListData(List<MealModel> meals){
		MealModel lastSelected = lstMeals.getSelectedValue();

		DefaultListModel<MealModel> listModel = new DefaultListModel<>();
		meals.stream().forEach(meal -> listModel.addElement(meal));
		lstMeals.setModel(listModel);

		if (meals.contains(lastSelected)) {
			lstMeals.setSelectedValue(lastSelected, true);
		}

	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAddMeal;
        private javax.swing.JButton btnCancel;
        private javax.swing.JButton btnSelect;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel lblSearch;
        private javax.swing.JLabel lblTitle;
        private javax.swing.JList<MealModel> lstMeals;
        private javax.swing.JTextField tfSearch;
        // End of variables declaration//GEN-END:variables
}
