/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Page;

import Model.ItemModel;
import Model.RecipeModel;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author micah
 */
public class RecipePageView extends javax.swing.JPanel {

	/**
	 * Creates new form RecipePageView
	 */
	public RecipePageView() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jProgressBar1 = new javax.swing.JProgressBar();
                txtNameSearch = new javax.swing.JTextField();
                txtCategorySearch = new javax.swing.JTextField();
                txtIngredientSearch = new javax.swing.JTextField();
                paneRecipeList = new javax.swing.JScrollPane();
                lstRecipes = new javax.swing.JList<>();
                lblRecipes = new javax.swing.JLabel();
                lblNameFilter = new javax.swing.JLabel();
                lblCategoryFilter = new javax.swing.JLabel();
                lblIngredientsFilter = new javax.swing.JLabel();
                recipeViewPanel = new javax.swing.JPanel();
                lblRecipeName = new javax.swing.JLabel();
                lblCategoryName = new javax.swing.JLabel();
                paneInstructions = new javax.swing.JScrollPane();
                taInstructions = new javax.swing.JTextArea();
                jSeparator1 = new javax.swing.JSeparator();
                lblInstructions = new javax.swing.JLabel();
                lblIngredientsList = new javax.swing.JLabel();
                paneIngredientsList = new javax.swing.JScrollPane();
                lstIngredients = new javax.swing.JList<>();
                jSeparator2 = new javax.swing.JSeparator();

                txtNameSearch.setToolTipText("ex: Burger");

                txtCategorySearch.setToolTipText("ex: Dinner, Brunch");

                txtIngredientSearch.setToolTipText("ex: spinach, tomatoe, rice...");

                lstRecipes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                paneRecipeList.setViewportView(lstRecipes);

                lblRecipes.setText("Recipes");

                lblNameFilter.setText("Name");

                lblCategoryFilter.setText("Category");

                lblIngredientsFilter.setText("Ingredients");

                lblRecipeName.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
                lblRecipeName.setText("Sample Recipe Name");

                lblCategoryName.setFont(new java.awt.Font("Chandas", 2, 18)); // NOI18N
                lblCategoryName.setText("Sample Category");

                taInstructions.setEditable(false);
                taInstructions.setColumns(20);
                taInstructions.setRows(5);
                taInstructions.setText("1. do something to food\n2. do something else to food\n3. do something more else to food");
                paneInstructions.setViewportView(taInstructions);

                lblInstructions.setText("Instructions");

                lblIngredientsList.setText("Ingredients");

                lstIngredients.setBackground(new java.awt.Color(241, 241, 241));
                lstIngredients.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                paneIngredientsList.setViewportView(lstIngredients);

                javax.swing.GroupLayout recipeViewPanelLayout = new javax.swing.GroupLayout(recipeViewPanel);
                recipeViewPanel.setLayout(recipeViewPanelLayout);
                recipeViewPanelLayout.setHorizontalGroup(
                        recipeViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(recipeViewPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(recipeViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblRecipeName, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                                        .addGroup(recipeViewPanelLayout.createSequentialGroup()
                                                .addGroup(recipeViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jSeparator1)
                                                        .addComponent(lblCategoryName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(recipeViewPanelLayout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(lblInstructions)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(lblIngredientsList)
                                                                .addGap(8, 8, 8))
                                                        .addGroup(recipeViewPanelLayout.createSequentialGroup()
                                                                .addComponent(paneInstructions)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(paneIngredientsList, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addContainerGap())))
                );
                recipeViewPanelLayout.setVerticalGroup(
                        recipeViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(recipeViewPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblRecipeName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(recipeViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblIngredientsList)
                                        .addComponent(lblInstructions))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(recipeViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(paneInstructions)
                                        .addGroup(recipeViewPanelLayout.createSequentialGroup()
                                                .addComponent(paneIngredientsList, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                                                .addContainerGap())))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblNameFilter))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtCategorySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblCategoryFilter))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(lblIngredientsFilter)
                                                                .addGap(437, 500, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(txtIngredientSearch)
                                                                .addContainerGap())))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(paneRecipeList, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblRecipes))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(recipeViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap())))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator2))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblNameFilter)
                                        .addComponent(lblCategoryFilter)
                                        .addComponent(lblIngredientsFilter))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCategorySearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtIngredientSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblRecipes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(recipeViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(paneRecipeList))
                                .addContainerGap())
                );
        }// </editor-fold>//GEN-END:initComponents


	public void setFilterListeners(DocumentListener listener){
		txtCategorySearch.getDocument().addDocumentListener(listener);
		txtIngredientSearch.getDocument().addDocumentListener(listener);
		txtNameSearch.getDocument().addDocumentListener(listener);
	}

	public void setRecipeListListener(ListSelectionListener listener){
		lstRecipes.addListSelectionListener(listener);
	}

	public void setIngredientListListener(ListSelectionListener listener){
		lstIngredients.addListSelectionListener(listener);
	}


	public String getCategoryText(){
		return this.txtCategorySearch.getText();
	}


	public String getNameText(){
		return this.txtNameSearch.getText();
	}

	public String getIngredientText(){
		return this.txtIngredientSearch.getText();
	}

	public void setRecipeList(List<RecipeModel> recipes){
		DefaultListModel<RecipeModel> listModel = new DefaultListModel<>();
		for (RecipeModel recipe : recipes){
			listModel.addElement(recipe);
		}
		lstRecipes.setModel(listModel);
	}

	public void setIngredientsList(List<ItemModel> ingredients){
		DefaultListModel<ItemModel> listModel = new DefaultListModel<>();
		for (ItemModel ingredient : ingredients){
			listModel.addElement(ingredient);
		}
		lstIngredients.setModel(listModel);
	}


	private void setupVisiblityForSelectedRecipe(boolean recipeIsSelected){
		lblIngredientsList.setVisible(recipeIsSelected);
		lstIngredients.setVisible(recipeIsSelected);
		lblInstructions.setVisible(recipeIsSelected);
		taInstructions.setVisible(recipeIsSelected);
	}

	private void setupForNoSelectedRecipe(){
		setupVisiblityForSelectedRecipe(false);
	}

	private void setupForSelectedRecipe(){
		setupVisiblityForSelectedRecipe(true);
	}

	public void showItemDetailsDialog(ItemModel item){
		System.out.println("item details");
	}

	public void clearSelectedIngredient(){
		lstIngredients.clearSelection();
	}

	public void setSelectedRecipe(RecipeModel recipe){
		if(recipe == null) {
			setupForNoSelectedRecipe();
			lblRecipeName.setText("No recipe selected...");
			lblCategoryName.setText("Select a recipe from the list to view its information");
			return;
		}
		setupForSelectedRecipe();


		lblRecipeName.setText(recipe.getName());
		lblCategoryName.setText(recipe.getCategory());
		taInstructions.setText(recipe.getInstructions());

		setIngredientsList(recipe.getIngredients());
		
	}




        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JProgressBar jProgressBar1;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JSeparator jSeparator2;
        private javax.swing.JLabel lblCategoryFilter;
        private javax.swing.JLabel lblCategoryName;
        private javax.swing.JLabel lblIngredientsFilter;
        private javax.swing.JLabel lblIngredientsList;
        private javax.swing.JLabel lblInstructions;
        private javax.swing.JLabel lblNameFilter;
        private javax.swing.JLabel lblRecipeName;
        private javax.swing.JLabel lblRecipes;
        private javax.swing.JList<ItemModel> lstIngredients;
        private javax.swing.JList<RecipeModel> lstRecipes;
        private javax.swing.JScrollPane paneIngredientsList;
        private javax.swing.JScrollPane paneInstructions;
        private javax.swing.JScrollPane paneRecipeList;
        private javax.swing.JPanel recipeViewPanel;
        private javax.swing.JTextArea taInstructions;
        private javax.swing.JTextField txtCategorySearch;
        private javax.swing.JTextField txtIngredientSearch;
        private javax.swing.JTextField txtNameSearch;
        // End of variables declaration//GEN-END:variables
}
